# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 621)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.PBExit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBExit.sizePolicy().hasHeightForWidth())
        self.PBExit.setSizePolicy(sizePolicy)
        self.PBExit.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBExit.setObjectName("PBExit")
        self.gridLayout.addWidget(self.PBExit, 5, 0, 1, 2)
        self.PBCorrect = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBCorrect.sizePolicy().hasHeightForWidth())
        self.PBCorrect.setSizePolicy(sizePolicy)
        self.PBCorrect.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"background-color: rgb(118, 255, 111);")
        self.PBCorrect.setObjectName("PBCorrect")
        self.gridLayout.addWidget(self.PBCorrect, 2, 1, 1, 1)
        self.TBShow = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBShow.sizePolicy().hasHeightForWidth())
        self.TBShow.setSizePolicy(sizePolicy)
        self.TBShow.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.TBShow.setObjectName("TBShow")
        self.gridLayout.addWidget(self.TBShow, 0, 0, 1, 2)
        self.PBTranslate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBTranslate.sizePolicy().hasHeightForWidth())
        self.PBTranslate.setSizePolicy(sizePolicy)
        self.PBTranslate.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBTranslate.setObjectName("PBTranslate")
        self.gridLayout.addWidget(self.PBTranslate, 4, 0, 1, 2)
        self.PBReplay = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBReplay.sizePolicy().hasHeightForWidth())
        self.PBReplay.setSizePolicy(sizePolicy)
        self.PBReplay.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBReplay.setObjectName("PBReplay")
        self.gridLayout.addWidget(self.PBReplay, 3, 0, 1, 2)
        self.PBWrong = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBWrong.sizePolicy().hasHeightForWidth())
        self.PBWrong.setSizePolicy(sizePolicy)
        self.PBWrong.setStyleSheet("font: 87 16pt \"Arial Black\";\n"
"background-color: rgb(255, 131, 131);")
        self.PBWrong.setObjectName("PBWrong")
        self.gridLayout.addWidget(self.PBWrong, 2, 0, 1, 1)
        self.TBGrade = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBGrade.sizePolicy().hasHeightForWidth())
        self.TBGrade.setSizePolicy(sizePolicy)
        self.TBGrade.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.TBGrade.setObjectName("TBGrade")
        self.gridLayout.addWidget(self.TBGrade, 1, 0, 1, 2)
        self.gridLayout.setRowStretch(0, 6)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 2)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(4, 2)
        self.gridLayout.setRowStretch(5, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PBExit.setText(_translate("MainWindow", "Exit"))
        self.PBCorrect.setText(_translate("MainWindow", "Correct"))
        self.PBTranslate.setText(_translate("MainWindow", "Translate"))
        self.PBReplay.setText(_translate("MainWindow", "Replay"))
        self.PBWrong.setText(_translate("MainWindow", "Wrong"))
