# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TBShow = QtWidgets.QTextBrowser(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TBShow.sizePolicy().hasHeightForWidth())
        self.TBShow.setSizePolicy(sizePolicy)
        self.TBShow.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.TBShow.setObjectName("TBShow")
        self.verticalLayout_2.addWidget(self.TBShow)
        self.PBNext = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBNext.sizePolicy().hasHeightForWidth())
        self.PBNext.setSizePolicy(sizePolicy)
        self.PBNext.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBNext.setObjectName("PBNext")
        self.verticalLayout_2.addWidget(self.PBNext)
        self.PBPlayer = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBPlayer.sizePolicy().hasHeightForWidth())
        self.PBPlayer.setSizePolicy(sizePolicy)
        self.PBPlayer.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBPlayer.setObjectName("PBPlayer")
        self.verticalLayout_2.addWidget(self.PBPlayer)
        self.PBTranslate = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBTranslate.sizePolicy().hasHeightForWidth())
        self.PBTranslate.setSizePolicy(sizePolicy)
        self.PBTranslate.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBTranslate.setObjectName("PBTranslate")
        self.verticalLayout_2.addWidget(self.PBTranslate)
        self.PBExit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PBExit.sizePolicy().hasHeightForWidth())
        self.PBExit.setSizePolicy(sizePolicy)
        self.PBExit.setStyleSheet("font: 87 16pt \"Arial Black\";")
        self.PBExit.setObjectName("PBExit")
        self.verticalLayout_2.addWidget(self.PBExit)
        self.verticalLayout_2.setStretch(0, 5)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PBNext.setText(_translate("MainWindow", "Next"))
        self.PBPlayer.setText(_translate("MainWindow", "Play"))
        self.PBTranslate.setText(_translate("MainWindow", "Translate"))
        self.PBExit.setText(_translate("MainWindow", "Exit"))
